Repository thoth-station/amun-client, pull requests merged in 2018-10, with the labels that each got.

#6 Initial dependency lock
  Pipfile.lock
Labels: bot, size/M

#7 Regenerate swagger client respecting new swagger specification
  Documentation/AnalysisUnfinishedResultResponseStatus.md
  Documentation/InspectionApi.md
  Documentation/InspectionBuildStatusResponse.md
  Documentation/InspectionBuildStatusResponseStatus.md
  Documentation/InspectionJobLogResponse.md
  Documentation/InspectionJobStatusResponse.md
  Documentation/InspectionJobStatusResponseStatus.md
  Documentation/InspectionRunLogResponse.md
  Documentation/InspectionRunStatusResponseStatus.md
  amun/swagger_client/__init__.py
  amun/swagger_client/amun/inspection_api.py
  amun/swagger_client/models/__init__.py
  amun/swagger_client/models/analysis_unfinished_result_response_status.py
  amun/swagger_client/models/inspection_build_status_response.py
  amun/swagger_client/models/inspection_build_status_response_status.py
  amun/swagger_client/models/inspection_job_log_response.py
  amun/swagger_client/models/inspection_run_log_response.py
  swagger-codegen.sh
Labels: size/XL

#8 Update README file
  README.md
  README.rst
Labels: approved, size/M

#12 State how to configure the rest client
  README.rst
Labels: approved, size/S

#15 Create a simple wrapper for analysis submission
  README.rst
  amun/__init__.py
  amun/lib.py
Labels: approved, size/M
