Repository thoth-station/amun-client, pull requests merged in 2018-11, with the labels that each got.

#24 Release of version 0.1.0
  CHANGELOG.md
  amun/__init__.py
Labels: approved, bot, size/S

#16 zuul, coala and github std configs
  .coafile
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .zuul.yaml
Labels: approved, size/M

#17 Automatic update of dependency certifi from 2018.8.24 to 2018.10.15
  Pipfile.lock
Labels: bot

#22 Automatic update of dependency python-dateutil from 2.7.3 to 2.7.5
  Pipfile.lock
Labels: bot

#27 Release of version 0.1.1
  CHANGELOG.md
  amun/__init__.py
Labels: bot, size/S

#28 Add hardware to requests
  Documentation/InspectionApi.md
  Documentation/InspectionSpecificationBuildRequests.md
  Documentation/InspectionSpecificationBuildRequestsHardware.md
  Documentation/InspectionSpecificationResponse.md
  Documentation/InspectionSpecificationResponseSpecification.md
  Documentation/InspectionSpecificationRunRequests.md
  Documentation/InspectionSpecificationRunRequestsHardware.md
  amun/swagger_client/__init__.py
  amun/swagger_client/amun/inspection_api.py
  amun/swagger_client/models/__init__.py
  amun/swagger_client/models/inspection_specification_build_requests.py
  amun/swagger_client/models/inspection_specification_build_requests_hardware.py
  amun/swagger_client/models/inspection_specification_response.py
  amun/swagger_client/models/inspection_specification_response_specification.py
  amun/swagger_client/models/inspection_specification_run_requests.py
  amun/swagger_client/models/inspection_specification_run_requests_hardware.py
Labels: size/XXL

#30 Release of version 0.1.2
  CHANGELOG.md
  amun/__init__.py
Labels: bot, size/XS

#35 Release of version 0.2.0
  CHANGELOG.md
  amun/__init__.py
Labels: bot, size/S

#37 Automatic update of dependency certifi from 2018.10.15 to 2018.11.29
  Pipfile.lock
Labels: bot
