Repository thoth-station/amun-client, pull requests merged in 2020-01, with the labels that each got.

#76 Happy new year!
  amun/__init__.py
  amun/lib.py
Labels: approved, size/XS

#67 Use codegen compatible with OpenAPI v3
  swagger-codegen.sh
Labels: size/XS

#79 Remove duplicit version identifier causing issues with Kebechet
  amun/swagger_client/__init__.py
  openapi-codegen.sh
Labels: approved, size/XS

#80 Release of version 0.3.0
  CHANGELOG.md
  amun/__init__.py
Labels: bot, size/S

#83 Release of version 0.3.1
  CHANGELOG.md
  amun/__init__.py
Labels: bot, size/XS

#84 Automatic update of dependency six from 1.13.0 to 1.14.0
  Pipfile.lock
Labels: bot, size/XS

#85 Add missing identifier parameter
  amun/lib.py
Labels: size/XS

#87 Release of version 0.3.2
  CHANGELOG.md
  amun/__init__.py
Labels: bot, size/XS

#89 Missing python_packages parameter
  amun/lib.py
Labels: approved, size/XS

#91 Release of version 0.3.3
  CHANGELOG.md
  amun/__init__.py
Labels: bot, size/XS

#92 Add missing parameters
  amun/lib.py
Labels: approved, size/XS

#94 Release of version 0.3.4
  CHANGELOG.md
  amun/__init__.py
Labels: approved, bot, size/XS

#95 Fix typo in variable name
  amun/lib.py
Labels: approved, size/S

#99 Release of version 0.3.5
  CHANGELOG.md
  amun/__init__.py
Labels: bot, size/XS

#100 Automatic update of dependency urllib3 from 1.25.7 to 1.25.8
  Pipfile.lock
Labels: bot, size/XS

#101 Fix syncing logic of inspections
  amun/lib.py
Labels: approved, size/S

#103 Release of version 0.3.6
  CHANGELOG.md
  amun/__init__.py
Labels: bot, size/XS

#104 Fix inspection syncing logic
  amun/lib.py
Labels: size/S

#106 Release of version 0.3.7
  CHANGELOG.md
  amun/__init__.py
Labels: bot, size/XS

#107 Finally sync Amun inspection sync
  amun/lib.py
Labels: approved, size/XS

#109 Release of version 0.3.8
  CHANGELOG.md
  amun/__init__.py
Labels: bot, size/XS
