Repository thoth-station/amun-client, pull requests merged in 2020-02, with the labels that each got.

#110 Updated OpenAPI codegen
  openapi-codegen.sh
Labels: approved, size/XS

#112 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#114 Release of version 0.4.0
  CHANGELOG.md
  amun/__init__.py
Labels: bot, size/XS

#116 Add issue templates
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
Labels: size/M

#119 Regenerate client library
  Documentation/DebugApi.md
  Documentation/InspectionApi.md
  Documentation/InspectionJobLogResponseLog.md
  Documentation/InspectionJobLogsResponse.md
  Documentation/InspectionJobLogsResponseLogs.md
  Documentation/InspectionResponse.md
  Documentation/InspectionResponseError.md
  Documentation/InspectionSpecification.md
  Documentation/InspectionSpecificationBuildRequests.md
  Documentation/InspectionSpecificationFiles.md
  Documentation/InspectionSpecificationResponse.md
  Documentation/InspectionSpecificationRunRequests.md
  Documentation/InspectionWorkflowParameters.md
  amun/swagger_client/__init__.py
  amun/swagger_client/configuration.py
  amun/swagger_client/models/__init__.py
  amun/swagger_client/models/inspection_job_log_response_log.py
  amun/swagger_client/models/inspection_job_logs_response.py
  amun/swagger_client/models/inspection_job_logs_response_logs.py
  amun/swagger_client/models/inspection_response.py
  amun/swagger_client/models/inspection_response_error.py
  amun/swagger_client/models/inspection_specification.py
  amun/swagger_client/models/inspection_specification_build_requests.py
  amun/swagger_client/models/inspection_specification_files.py
  amun/swagger_client/models/inspection_specification_response.py
  amun/swagger_client/models/inspection_specification_run_requests.py
  amun/swagger_client/models/inspection_workflow_parameters.py
Labels: size/XXL

#117 Release of version 0.4.1
  CHANGELOG.md
  amun/__init__.py
Labels: bot, size/XS

#123 Fix coala complains
  amun/swagger_client/__init__.py
Labels: size/XS

#122 Release of version 0.4.2
  CHANGELOG.md
  amun/__init__.py
Labels: bot, size/XS

#120 We use HTTPS
  openapi-codegen.sh
Labels: size/XS

#124 Regenerate with package manager
  Documentation/InspectionSpecification.md
  amun/swagger_client/models/inspection_specification.py
Labels: size/M

#126 Release of version 0.4.3
  CHANGELOG.md
  amun/__init__.py
Labels: bot, size/XS
